---
- hosts: all

  become: true
  tasks:
    - name: update apt packages
      apt:
        upgrade: dist
        update_cache: yes
    - name: Check if reboot required
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file

    - name: Reboot if required
      reboot:
      when: reboot_required_file.stat.exists == true